improved error handling

diff --git a/usr/libexec/systemcheck/get-password-status-list b/usr/libexec/systemcheck/get-password-status-list
--- a/usr/libexec/systemcheck/get-password-status-list
+++ b/usr/libexec/systemcheck/get-password-status-list
@@ -5,7 +5,13 @@
 
 source /usr/libexec/helper-scripts/accountctl.sh
 
-readarray -t user_list < <(/usr/libexec/helper-scripts/get-user-list)
+if ! output=$(/usr/libexec/helper-scripts/get-user-list); then
+    echo "ERROR: Failed to get user list!" >&2
+    exit 1
+fi
+
+readarray -t user_list <<< "$output"
+
 for user in "${user_list[@]}"; do
    if [ -n "$(get_pass "${user}")" ]; then
       echo 'Present'
