Add 'Locked (Present)' and 'Restricted (Present)' password statuses

diff --git a/usr/libexec/systemcheck/get-password-status-list b/usr/libexec/systemcheck/get-password-status-list
--- a/usr/libexec/systemcheck/get-password-status-list
+++ b/usr/libexec/systemcheck/get-password-status-list
@@ -6,7 +6,7 @@
 source /usr/libexec/helper-scripts/accountctl.sh
 
 if ! output="$(/usr/libexec/helper-scripts/get-user-list)"; then
-    echo "ERROR: Failed to get user list!" >&2
+    printf '%s\n' "ERROR: Failed to get user list!" >&2
     exit 1
 fi
 
@@ -14,15 +14,24 @@ readarray -t user_list <<< "$output"
 
 for user in "${user_list[@]}"; do
    pass_data="$(get_pass "${user}")"
+   pass_status=""
    if [ -n "${pass_data}" ]; then
       if [ "${pass_data:0:1}" = '!' ]; then
-         echo 'Locked'
+         pass_status='Locked'
+         if [ -n "${pass_data:1:1}" ]; then
+           pass_status+=' (Present)'
+         fi
       elif [ "${pass_data:0:1}" = '*' ]; then
-         echo 'Restricted'
+         pass_status='Restricted'
+         if [ -n "${pass_data:1:1}" ]; then
+           pass_status+=' (Present)'
+         fi
       else
-         echo 'Present'
+         pass_status='Present'
       fi
    else
-      echo 'Absent'
+      pass_status='Absent'
    fi
+
+   printf '%s\n' "${pass_status}"
 done
