fix

diff --git a/usr/lib/systemcheck/census b/usr/lib/systemcheck/census
--- a/usr/lib/systemcheck/census
+++ b/usr/lib/systemcheck/census
@@ -9,8 +9,8 @@ set -e
 source /usr/lib/systemcheck/uwt_tool.bsh
 
 census_preparation() {
-   if [ ! "$(whoami)" = "sal-census" ] && [ ! "$(whoami)" = "systemcheck" ]; then
-      echo "ERROR: Exiting. Must be run under user sal-census or systemcheck."
+   if [ ! "$(whoami)" = "sal-census" ] && [ ! "$(whoami)" = "census" ]; then
+      echo "ERROR: Exiting. Must be run under user sal-census or census."
       exit 1
    fi
 
@@ -67,6 +67,9 @@ census_preparation() {
    fi
 
    [ -n "$CURL_PROXY_CENSUS" ] || CURL_PROXY_CENSUS="--proxy socks5h://user:password@$GATEWAY_IP:$SOCKS_PORT_CENSUS"
+
+   ls -la ~/
+   touch ~/census_last_done
 }
 
 check_circuit_established() {
@@ -91,8 +94,8 @@ check_census_lastrun() {
    ## A day has 86400 seconds.
    local MAX="86400"
 
-   if [ -f ~/census/last_done ]; then
-      LASTRUN="$(cat ~/census/last_done)" || true
+   if [ -f ~/census_last_done ]; then
+      LASTRUN="$(cat ~/census_last_done)" || true
    fi
 
    if [ "$LASTRUN" = "" ]; then
@@ -132,7 +135,7 @@ check_census_lastrun() {
 census_completed() {
    local LASTRUN
    LASTRUN="$(date --utc +%s)"
-   echo "$LASTRUN" | tee ~/census/last_done > /dev/null
+   echo "$LASTRUN" | tee ~/census_last_done > /dev/null
 }
 
 census_count_or_not() {
@@ -159,10 +162,8 @@ census_count_or_not() {
 }
 
 census_do() {
-   mkdir --parents ~/census
-
-   #rm -f ~/census/census_result.txt
-   #--output ~/census/census_result.txt
+   #rm -f ~/census_result
+   #--output ~/census_result
 
    curl_exit_code="0"
 
