refactoring, drop legacy config folder in /rw

diff --git a/usr/lib/systemcheck/census-daemon b/usr/lib/systemcheck/census-daemon
--- a/usr/lib/systemcheck/census-daemon
+++ b/usr/lib/systemcheck/census-daemon
@@ -10,17 +10,20 @@ if [ -f /etc/default/systemcheckd ]; then
 fi
 
 shopt -s nullglob
-for i in /etc/default/systemcheckd.d/*.conf /rw/config/default/systemcheckd.d/*.conf /usr/local/etc/default/systemcheckd.d/*.conf; do
-   bash_n_exit_code="0"
-   bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
-   if [ ! "$bash_n_exit_code" = "0" ]; then
-      echo "Invalid config file: $i
-bash_n_exit_code: $bash_n_exit_code
-bash_n_output:
-$bash_n_output" >&2
-      exit 1
-   fi
-   source "$i"
+for i in \
+   /etc/default/systemcheckd.d/*.conf \
+   /usr/local/etc/default/systemcheckd.d/*.conf \
+   ; do
+      bash_n_exit_code="0"
+      bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
+      if [ ! "$bash_n_exit_code" = "0" ]; then
+         echo "Invalid config file: $i
+   bash_n_exit_code: $bash_n_exit_code
+   bash_n_output:
+   $bash_n_output" >&2
+         exit 1
+      fi
+      source "$i"
 done
 
 if [ "$debugging" = "true" ]; then
